services:
    fgc_menu.manager:
        class: FGC\MenuBundle\Util\MenuManager
        arguments: ["@fgc_menu.discovery"]
    fgc_menu.discovery:
        class: FGC\MenuBundle\Util\MenuDiscovery
        arguments: ["%fgc_menu.config%", "@event_dispatcher"]
