services:
    fgc_menu.twig.function:
        class: FGC\MenuBundle\Twig\MenuRenderExtension
        arguments: ["@fgc_menu.twig.render"]
        tags: ["twig.extension"]
    fgc_menu.twig.render:
        class: FGC\MenuBundle\Util\MenuRender
        arguments: ["@fgc_menu.manager", "@twig"]